name: CI Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_path:
        description: 'Path to the test folder'
        required: true
        default: 'python-code/tests'
      terraform_path:
        description: 'Path to the Terraform folder'
        required: true
        default: 'terraform-code'

env:
  TERRAFORM_DIR: ${{ inputs.terraform_path || 'terraform-code' }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  test-and-plan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write
      statuses: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.10.5'

    - name: Run Python Tests
      id: run_tests
      run: |
        pytest ${{ inputs.test_path || 'python-code/tests' }} || echo "TEST_FAILED=true" >> $GITHUB_ENV
      continue-on-error: true
  
    - name: Comment on PR if tests fail
      if: env.TEST_FAILED == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: "⚠️ Python tests failed! Please check the logs and fix the issues before merging."
          });

    - name: Fail the workflow if tests failed
      if: env.TEST_FAILED == 'true'
      run: exit 1

