name: Test and Terraform Plan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Add environment variables
    - name: Set OpenAI API Key
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

    # Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio

    # Run pytest
    - name: Run Python Tests
      run: pytest ${{ inputs.test_path }}

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.10.5'
    
    # ✅ Configure AWS Credentials
    - name: Configure AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

    # Generate SSH key pair for Terraform
    - name: Generate SSH Key
      run: |
        ssh-keygen -t rsa -b 4096 -f terraform-code/my-terraform-key -N ""

    # Initialize Terraform
    - name: Terraform Init
      run: |
        cd ${{ inputs.terraform_path }}
        terraform init

    # Run Terraform Plan and output to PR
    - name: Terraform Plan
      run: |
        cd ${{ inputs.terraform_path }}
        terraform plan -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="aws_region=${{ secrets.AWS_REGION }}" -out=tfplan
        terraform show -json tfplan > plan.json

    # Add Terraform Plan output to PR
    - name: Comment Terraform Plan on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const plan = fs.readFileSync('${{ inputs.terraform_path }}/plan.json', 'utf8');

          if (!context.payload.pull_request) {
            console.log("Skipping PR comment - not a pull request event.");
            return;
          }

          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `### Terraform Plan Output\n\`\`\`json\n${plan}\n\`\`\``
          });


  # ✅ Stage 2: Deploy on Merge to Main
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test-and-plan  # Ensure PR checks passed before applying
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.10.5'

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

    # Initialize Terraform
    - name: Terraform Init
      run: |
        cd ${{ inputs.terraform_path }}
        terraform init

    # ✅ Apply Terraform Changes Only if PR Passed
    - name: Terraform Apply
      run: |
        cd ${{ inputs.terraform_path }}
        terraform apply
