name: CI/CD Pipeline - Test & Deploy Terraform

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_path:
        description: 'Path to the test folder'
        required: true
        default: 'python-code/tests'
      terraform_path:
        description: 'Path to the Terraform folder'
        required: true
        default: 'terraform-code'

jobs:
  # ✅ Stage 1: Run Tests and Terraform Plan
  test-and-plan:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write  # ✅ Allow commenting on PR

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # ✅ Set Terraform Path
    - name: Set Terraform Path
      run: echo "TERRAFORM_DIR=${{ github.event.inputs.terraform_path || 'terraform-code' }}" >> $GITHUB_ENV

    # ✅ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # ✅ Install Dependencies
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio

    # ✅ Run Tests
    - name: Run Python Tests
      run: pytest ${{ github.event.inputs.test_path || 'python-code/tests' }}

    # ✅ Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.10.5'

    # ✅ Configure AWS Credentials
    - name: Configure AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

    # ✅ Terraform Init
    - name: Terraform Init
      run: |
        cd $TERRAFORM_DIR
        terraform init

    # ✅ Run Terraform Plan
    - name: Terraform Plan
      run: |
        cd $TERRAFORM_DIR
        terraform plan -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
                       -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
                       -var="aws_region=${{ secrets.AWS_REGION }}" \
                       -out=tfplan
        terraform show -json tfplan > plan.json

    # ✅ Comment Terraform Plan on PR
    - name: Comment Terraform Plan on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');

          // Read the Terraform Plan output
          const planPath = process.env.TERRAFORM_DIR + '/plan.json';
          let plan = fs.readFileSync(planPath, 'utf8');

          // Mask sensitive values
          plan = plan.replace(/"aws_access_key":\{"value":"(.*?)"\}/g, '"aws_access_key":{"value":"***MASKED***"}');
          plan = plan.replace(/"aws_secret_key":\{"value":"(.*?)"\}/g, '"aws_secret_key":{"value":"***MASKED***"}');

          if (!context.payload.pull_request) {
            console.log("Skipping PR comment - not a pull request event.");
            return;
          }

          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `### Terraform Plan Output\n\`\`\`json\n${plan}\n\`\`\``
          });

  # ✅ Stage 2: Apply Terraform on Merge to Main
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test-and-plan  # Ensure PR checks pass before deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # ✅ Set Terraform Path
    - name: Set Terraform Path
      run: echo "TERRAFORM_DIR=${{ github.event.inputs.terraform_path || 'terraform-code' }}" >> $GITHUB_ENV

    # ✅ Debugging Info
    - name: Debugging Information
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Branch: ${{ github.ref }}"
        echo "Needs Test and Plan: ${{ needs.test-and-plan.result }}"
        echo "Terraform Directory: $TERRAFORM_DIR"

    # ✅ Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.10.5'

    # ✅ Configure AWS Credentials
    - name: Configure AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

    # ✅ Terraform Init
    - name: Terraform Init
      run: |
        cd $TERRAFORM_DIR
        terraform init

    # ✅ Terraform Plan
    - name: Terraform Plan
      run: |
        cd $TERRAFORM_DIR
        terraform plan -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
                       -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
                       -var="aws_region=${{ secrets.AWS_REGION }}" \
                       -out=tfplan
        terraform show -json tfplan > plan.json

    # ✅ Ensure No Terraform Locks
    - name: Unlock Terraform (If Needed)
      continue-on-error: true
      run: |
        cd $TERRAFORM_DIR
        terraform force-unlock $(terraform state list)

    # ✅ Apply Terraform Changes
    - name: Terraform Apply
      run: |
        cd $TERRAFORM_DIR
        terraform apply -auto-approve
