name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TERRAFORM_DIR: 'terraform-code'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.10.5'

    - name: Generate SSH Key Pair (If Not Exists)
      run: |
        if [ ! -f "$TERRAFORM_DIR/my-terraform-key" ]; then
          ssh-keygen -t rsa -b 4096 -f $TERRAFORM_DIR/my-terraform-key -N ""
        else
          echo "SSH key already exists. Skipping generation."
        fi

    - name: Terraform Init
      run: |
        cd $TERRAFORM_DIR
        terraform init

    - name: Terraform Apply
      run: |
        cd $TERRAFORM_DIR
        terraform apply -auto-approve -var="aws_access_key=${{ env.AWS_ACCESS_KEY_ID }}" \
                        -var="aws_secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}" \
                        -var="aws_region=${{ env.AWS_REGION }}"
